remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Test Title
description: Test Description
site:
  github:
    is_project_page: false
show_downloads: false
show_repository_url: false
  
